# Generated by Django 2.2.2 on 2019-07-14 21:26

from django.db import migrations


def update_db(apps, schema_editor):
    """ Updates titles for Article table """

    Article = apps.get_model('article', 'Article')
    for article in Article.objects.all():
        article.title = "Data migration title"
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190714_1007'),
    ]

    operations = [
        migrations.RunPython(update_db),
    ]
