# Generated by Django 2.2.2 on 2019-07-14 21:43

from django.db import migrations


def update_db(apps, schema_editor):
    """ Updates titles for Article table """

    Article = apps.get_model('article', 'Article')
    for article in Article.objects.all().iterator():
        article.title = "New migration"
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190714_2126'),
    ]

    operations = [
        migrations.RunPython(update_db),
    ]
