# Generated by Django 2.2.2 on 2019-07-16 10:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('article', '0006_auto_20190714_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of adding a comment')),
                ('moderation', models.BooleanField(default=False, verbose_name='moderation')),
                ('aricle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
