# Generated by Django 2.2.2 on 2019-07-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='aricle',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='description',
            new_name='comment',
        ),
    ]
