# Generated by Django 2.2.2 on 2019-07-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_comments_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('date',)},
        ),
    ]
