# Generated by Django 2.2.2 on 2019-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20190717_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of adding a comment'),
        ),
    ]
